### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by L1mbusFr1ng3** [Lifailon/RSA#2]
Hello,
Your code is absolutely amazing. I plan on tweaking it for some specific use case scenarios in our organization. I'll upload any changes as to share with you.

However, is there an English version? I obviouslyu can translate the readme etc. But does an english version or fork exist? Can you help?

Thanks,
Eric
edenholtz@lampsplus.com

**Comment by Lifailon** [comment]
Hello!
There is no English version of the README, as support has been discontinued due to lack of interest from the audience.

The interface itself was originally in Russian and has been translated in the latest version, there are variables at the beginning of the code that can be used to translate into another language, it was planned to add an external file to configure such a solution.

If you find such a solution useful, I might resume support.
Thanks for your interest, Eric!
